### ISSUE TITLE
Sælger med over til BC

### ISSUE THREAD

**Issue by JanSkrubbeltrang** [spysystem/msbc-spy-extension#3]
Primær i Spy til Kundes Sælger

**Comment by JanSkrubbeltrang** [comment]
"Salesperson Code" er en del af CustomerList Endpoint i dag

**Comment by jensbjerre** [comment]
Kan vi lave det sådan, at hvis den kode vi sender over ikke findes i BC bliver den ignoreret ?

**Comment by JanSkrubbeltrang** [comment]
jeg har forsøgt at lave en lytter der kigger på før man inserter i Customer og validerer Sales Person Code

**Comment by JanSkrubbeltrang** [comment]
Og det virkede ikke!, Lige meget hvad jeg forsøger, så fejler mit kald til at indsætte Sælger. Tror det bedte er at tjekket ligger i spy. Jeg kan udstille Sælger/Indkøbere til jer

**Comment by Nicolai-** [comment]
Der kan potentielt være flere sælgere på samme kunde på tværs af forskellige brands, og hvis BC kun kan tage en.

Så kan vi ikke vælge en korrekte, Mads, Jens og jeg har snakket den igennem og den bliver lukket her, det bliver ikke lavet.
