### ISSUE TITLE
Send PDF to BC

### ISSUE THREAD

**Issue by JanSkrubbeltrang** [spysystem/msbc-spy-extension#8]
Salgs/købs faktura

**Comment by JanSkrubbeltrang** [comment]
Kunne det være en ide at det faktisk er SPY der sender fakturaer ind i BC?

**Comment by jensbjerre** [comment]
Vi kan lave det på begge måder, hvad er det bedste/nemmeste ?

**Comment by JanSkrubbeltrang** [comment]
Tror det er nemmest at det komemr fra spy. Jeg har undersøgt det og lavet mockup til at man kan indsende data. Man laver bare et post kald til https://api.businesscentral.dynamics.com/v2.0/33f54721-646b-403b-ab17-3ba5df02a1a5/SPY-Udvikling/OData/SpyCreateJournalLine_uploadDocument med følgende JSON payload

{
    "documentType": "Invoice",
    "docNo": "SO12345",
    "data": "[Indsæt data fra faktura her]"
}

Så skal vi bare blive enige om hvilke documenttyper der skal modtages og jeg skal lige have fuld styr på hvor det er de skal vedhæftes

**Comment by Nicolai-** [comment]
Det er lavet i version 77 via IncomingDocument
